In [52]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(110)
x1= torch.randn((3,5), dtype=torch.float32)
w1= torch.randn((5,), dtype=torch.float32)

x= torch.tensor([[1. ,2. ,0. ,4. ,1.],
                 [0. ,1. ,1. ,1. ,1.],
                 [2. ,3. ,0. ,1. ,4.]])
w= torch.tensor([1., 0.5, 1., -1, -0.5])
b= torch.tensor(1.0)

In [3]:
x1

tensor([[-0.4542, -1.1170,  0.7534,  2.6707, -1.2473],
        [-0.8668,  0.1647, -0.1978, -1.1574, -0.0619],
        [-1.8319, -0.4143, -0.4898,  1.4640, -1.8555]])

In [4]:
w1

tensor([ 0.2380,  0.8970, -1.8386,  2.0783, -0.5478])

🔶activation function

In [7]:
def activation_linear(x):
    return x

🔶step function

In [8]:
def activation_step(x):
    if x>0:
        y= torch.tensor(1.)
    elif x<0:
        y=torch.tensor(0.)
    else:
        y=torch.tensor(0.5)
    return y
        

🔶neurun function

In [13]:
def neuron(x, w, b , af):
    z=0
    for xi,wi in zip(x,w):
        z += xi*wi
    z += b
    y = af(z)
    return y

In [14]:
print(x1[0])
print(x[0])

tensor([-0.4542, -1.1170,  0.7534,  2.6707, -1.2473])
tensor([1., 2., 0., 4., 1.])


In [15]:
neuron(x1[0], w1 , b , activation_linear)

tensor(4.7384)

In [16]:
neuron(x[0], w , b , activation_step) 

tensor(0.)

In [20]:
#(input , value)تابع پله
torch.heaviside(torch.tensor(-1.),torch.tensor(0.5))

tensor(0.)

🔶vectorization

In [ ]:
def neuron2(x , w , b ,af):
    #y= af(torch.matmul(x , w))
    y= af(x @ w + b)
    return y 

In [21]:
neuron(x[0], w , b , activation_step) 

tensor(0.)

🔶class neuron 

In [35]:
class Neuron:
    def __init__(self, m , af):
        self.w = torch.randn(m)
        self.b = torch.randn(1)
        self.af = af
    def __call__(self,x):
        y = self.af(x @ self.w + b)
        return y
    

In [38]:
neuron3 = Neuron(5, activation_linear)

In [40]:
neuron3(x[0])

tensor(9.9223)

✳️💠LOSS✅

In [44]:
yp = torch.randn((10,), dtype = torch.float32)
yt = torch.randn((10,), dtype = torch.float32)
yp

tensor([-0.5120, -1.1930,  0.2331,  0.3727,  0.1699,  0.5249,  1.4532, -0.4318,
        -0.4315,  0.6315])

💠from scratch

In [45]:
torch.mean((yp - yt)**2)

tensor(1.3802)

💠MSE in pytorch

In [48]:
#از این ادرس بصورت کلاس باید ازش استفاده کنیم
mse_loss = nn.MSELoss()
mse_loss(yp , yt)

tensor(1.3802)

💠MSE function

In [54]:
#از این ادرس بصورت فانکشی در دسترس هست
F.mse_loss(yp , yt)

tensor(1.3802)

In [ ]:
💠MAS loss in pytorch

In [56]:
MAE_loss = nn.L1Loss()
MAE_loss(yp , yt)

tensor(1.0212)

💠MAE function

In [57]:
F.l1_loss(yt , yp)

tensor(1.0212)

💠 connect loss to neuron

In [93]:
class Neuron:
    def __init__(self, m , af):
        torch.manual_seed(110)
        self.w = torch.randn(m)
        self.b = torch.randn(1)
        self.af = af
    def __call__(self , x):
        y = x @ self.w + self.b
        if self.af == 'linear':
            y = self.linear(y)
        elif self.af=='step':
            y = self.step(y)
        return y
    def linear(self , a):
        return a
    def step(self , b):
        if b>0 :
            y= torch.tensor(1.)
        elif b<0:
            y=torch.tensor(0.)
        else:
            y=torch.tensor(0.5)
        return y

In [97]:
x=torch.randn((3,5), dtype = torch.float32)
yt= torch.randn((3,), dtype = torch.float32)

x2= torch.tensor([[1. ,2. ,0. ,4. ,1.],
                 [0. ,1. ,1. ,1. ,1.],
                 [2. ,3. ,0. ,1. ,4.]])
yt2= torch.tensor([1., 2, 0.])

neuron4 = Neuron(5 , 'linear')
yp = neuron4(x2[0])

print(yt2[0:1])
print(yp)

loss= F.mse_loss(yp,yt2[0:1])
loss
 

tensor([1.])
tensor([5.8804])


tensor(23.8184)

✏️〽️autogradad ✏️

In [100]:
x = torch.tensor(3. , requires_grad=True)
y=x**2
y.backward()
x.grad
x.grad.zero_()

tensor(0.)