In [1]:
import torch

In [2]:
scaler= torch.tensor(2.5)
scaler

tensor(2.5000)

In [3]:
vector= torch.tensor([2.5 , 4 , 2 ,3])
vector

tensor([2.5000, 4.0000, 2.0000, 3.0000])

In [4]:
Martix= torch.tensor([[4.,5],[6,7],[8,9]])
Martix

tensor([[4., 5.],
        [6., 7.],
        [8., 9.]])

In [5]:
c_vector= torch.tensor([[1],[2],[3],[4]])
c_vector

tensor([[1],
        [2],
        [3],
        [4]])

In [6]:
Tensor_3d= torch.tensor([[[2,3],[5,6]],
                      [[7,8],[5,9]]])
Tensor_3d

tensor([[[2, 3],
         [5, 6]],

        [[7, 8],
         [5, 9]]])

In [7]:
scaler.dtype

torch.float32

In [8]:
Martix.dtype

torch.float32

In [9]:
 print(torch.tensor([-1 , 7] , dtype= torch.int16))

tensor([-1,  7], dtype=torch.int16)


In [10]:
 print(torch.tensor([-1,7]).dtype)

torch.int64


In [11]:
vec_int= torch.tensor([1 , 2] , dtype= torch.uint8)

vec_int= vec_int.bool()
vec_int.dtype

torch.bool

 #### device

In [12]:
#vec = torch.tensor([1,2] , device='cuda')
#vec = vec.cuda()
#vec = vec.cpu()
#vec

#### tensor attributes

In [13]:
Martix.shape

torch.Size([3, 2])

In [14]:
print(Martix.size())
print(Martix.size(0))
print(Martix.size(1))

torch.Size([3, 2])
3
2


In [15]:
Tensor_3d.max()

tensor(9)

In [16]:
Tensor_3d.float().mean()

tensor(5.6250)

In [17]:
Tensor_3d.float().std()

tensor(2.3867)

In [18]:
#transpose
M = torch.tensor([[4.,5],[6,7],[8,9]])
M.float().t()

tensor([[4., 6., 8.],
        [5., 7., 9.]])

#### special arreys

In [19]:
torch.ones((2,3), dtype=torch.int16)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [20]:
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

In [21]:
torch.eye(5,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
#define empty array
empty = torch.empty((2,3))
empty.fill_(1.2)

tensor([[1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000]])

In [23]:
empty.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [24]:
torch.full((3,2,2), 2.0)

tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])

In [25]:
torch.zeros_like(empty)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### random array

In [26]:
# rand between 0,1 and uniform distrubution
torch.rand((2,3))

tensor([[0.5339, 0.7957, 0.5751],
        [0.7407, 0.4944, 0.4982]])

In [27]:
#random normal=gausian distrubution mean=1 , var=1
torch.randn((2,4))

tensor([[ 1.4112, -1.0392,  0.2534,  0.2157],
        [ 1.1990, -1.1280,  1.2376,  0.6250]])

In [28]:
"""import matplotlib
matplotlib.use('Agg')  # Use a non-interactive backend
import matplotlib.pyplot as plt
import torch
%matplotlib inline"""

"import matplotlib\nmatplotlib.use('Agg')  # Use a non-interactive backend\nimport matplotlib.pyplot as plt\nimport torch\n%matplotlib inline"

In [29]:
"""rand_uniform= torch.rand(100)
rand_uniform
plt.hist(rand_uniform)"""

'rand_uniform= torch.rand(100)\nrand_uniform\nplt.hist(rand_uniform)'

In [30]:
"""rand_gauss= 2* torch.randn(100) + 1.5
plt.hist(rand_gauss,100)"""

'rand_gauss= 2* torch.randn(100) + 1.5\nplt.hist(rand_gauss,100)'

In [31]:
torch.randint(20,32,(2,5))

tensor([[31, 25, 23, 23, 28],
        [25, 20, 30, 30, 31]])

In [32]:
torch.randperm(20)

tensor([12,  6, 19,  9,  5, 11,  4, 17, 14, 18, 16,  1,  2,  3, 13,  8, 10, 15,
         7,  0])

In [33]:
torch.manual_seed(112)
torch.randperm(10)

tensor([4, 0, 2, 8, 5, 9, 7, 3, 1, 6])

#### indexing

In [36]:
a= torch.randn(5)
print(a)
a[0]


tensor([-0.5962,  0.4436,  0.4491,  2.0434, -0.9489])


tensor(-0.5962)

In [38]:
a[-1]

tensor(-0.9489)

In [41]:
b= torch.rand(5,3)
print(b)
b[1,2]

tensor([[0.4114, 0.0355, 0.5446],
        [0.8211, 0.8331, 0.8229],
        [0.6074, 0.3517, 0.1043],
        [0.2553, 0.9525, 0.3880],
        [0.0496, 0.9614, 0.6476]])


tensor(0.8229)

In [42]:
C = torch.randint(100, (3,2,2))
print(C)
C[0]

tensor([[[62, 45],
         [95,  9]],

        [[93, 82],
         [24, 77]],

        [[28, 95],
         [56, 55]]])


tensor([[62, 45],
        [95,  9]])

In [45]:
d = torch.randn(10)
print(d)
d[5:7]

tensor([-0.5434, -0.3937,  0.1892, -0.0560,  0.9069,  0.4922, -1.6926,  0.0150,
         0.5237,  0.0023])


tensor([ 0.4922, -1.6926])

In [47]:
d[0:-1]

tensor([-0.5434, -0.3937,  0.1892, -0.0560,  0.9069,  0.4922, -1.6926,  0.0150,
         0.5237])

In [48]:
d[3:]

tensor([-0.0560,  0.9069,  0.4922, -1.6926,  0.0150,  0.5237,  0.0023])

In [49]:
d[2::2]

tensor([ 0.1892,  0.9069, -1.6926,  0.5237])

In [50]:
d[[0,4,7,8]]

tensor([-0.5434,  0.9069,  0.0150,  0.5237])

In [52]:
b[::2,2]

tensor([0.5446, 0.1043, 0.6476])

In [54]:
#c[1,...]=c[1,:,:]
C[1,...]

tensor([[93, 82],
        [24, 77]])

#### mathematical operation

In [57]:
 a= torch.randint(10,(2,2))
 b= torch.randint(10,(2,2))
print(a)
print(b)

tensor([[9, 9],
        [5, 4]])
tensor([[8, 3],
        [7, 3]])


In [58]:
a+b

tensor([[17, 12],
        [12,  7]])

In [61]:
torch.add(a,b)

tensor([[17, 12],
        [12,  7]])

In [65]:
#ضرب درایه به درایه
torch.mul(a,b)

tensor([[72, 27],
        [35, 12]])

In [66]:
#ضرب ماتریسی
torch.matmul(a,b)

tensor([[135,  54],
        [ 68,  27]])

In [67]:
a@b

tensor([[135,  54],
        [ 68,  27]])

#### broadcasting

In [69]:
#adding a vactor with a scaler 
a= torch.randint(10,(1,2,3))
a

tensor([[[8, 8, 8],
         [6, 5, 5]]])

In [70]:
a + 2.

tensor([[[10., 10., 10.],
         [ 8.,  7.,  7.]]])

In [73]:
#add a vector with elements of matrix
m= torch.ones(3,3)
p= torch.arange(0,3)
k= torch.linspace(1,3,10)

In [74]:
p

tensor([0, 1, 2])

In [75]:
k

tensor([1.0000, 1.2222, 1.4444, 1.6667, 1.8889, 2.1111, 2.3333, 2.5556, 2.7778,
        3.0000])

In [76]:
m+p

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

#### dimention transformer

In [77]:
a= torch.randn(2,6)
b= torch.rand(3)
a

tensor([[-0.0300, -1.8528,  0.2264,  1.9142, -0.4472, -2.3587],
        [-1.6823,  2.3448, -0.1702, -0.0436, -1.5471, -1.2146]])

In [78]:
b

tensor([0.9868, 0.4942, 0.8037])

In [81]:
a.reshape((2,3,2))

tensor([[[-0.0300, -1.8528],
         [ 0.2264,  1.9142],
         [-0.4472, -2.3587]],

        [[-1.6823,  2.3448],
         [-0.1702, -0.0436],
         [-1.5471, -1.2146]]])

In [82]:
a.view((2,3,2))

tensor([[[-0.0300, -1.8528],
         [ 0.2264,  1.9142],
         [-0.4472, -2.3587]],

        [[-1.6823,  2.3448],
         [-0.1702, -0.0436],
         [-1.5471, -1.2146]]])

In [85]:
b.size()

torch.Size([3])

In [87]:
#turn anythibg into vector
a.view(-1)

tensor([-0.0300, -1.8528,  0.2264,  1.9142, -0.4472, -2.3587, -1.6823,  2.3448,
        -0.1702, -0.0436, -1.5471, -1.2146])

In [92]:
b.repeat(3,2)

tensor([[0.9868, 0.4942, 0.8037, 0.9868, 0.4942, 0.8037],
        [0.9868, 0.4942, 0.8037, 0.9868, 0.4942, 0.8037],
        [0.9868, 0.4942, 0.8037, 0.9868, 0.4942, 0.8037]])

In [96]:
#concatinate
torch.cat((a,a))

tensor([[-0.0300, -1.8528,  0.2264,  1.9142, -0.4472, -2.3587],
        [-1.6823,  2.3448, -0.1702, -0.0436, -1.5471, -1.2146],
        [-0.0300, -1.8528,  0.2264,  1.9142, -0.4472, -2.3587],
        [-1.6823,  2.3448, -0.1702, -0.0436, -1.5471, -1.2146]])

In [97]:
torch.cat((a,a),dim=1)

tensor([[-0.0300, -1.8528,  0.2264,  1.9142, -0.4472, -2.3587, -0.0300, -1.8528,
          0.2264,  1.9142, -0.4472, -2.3587],
        [-1.6823,  2.3448, -0.1702, -0.0436, -1.5471, -1.2146, -1.6823,  2.3448,
         -0.1702, -0.0436, -1.5471, -1.2146]])

In [109]:
# add one dimention in the given dimention
n = a.unsqueeze(2)
n

tensor([[[-0.0300],
         [-1.8528],
         [ 0.2264],
         [ 1.9142],
         [-0.4472],
         [-2.3587]],

        [[-1.6823],
         [ 2.3448],
         [-0.1702],
         [-0.0436],
         [-1.5471],
         [-1.2146]]])

In [110]:
n.shape

torch.Size([2, 6, 1])

In [112]:
#delete added dimention with size one
n.squeeze(-1).shape

torch.Size([2, 6])

#### bult-in function

In [128]:
q= torch.randint(10,(4,4))
q

tensor([[1, 8, 6, 5],
        [3, 8, 6, 9],
        [2, 5, 3, 6],
        [5, 3, 6, 9]])

In [129]:
torch.sum(q)

tensor(85)

In [130]:
#جمع در راستای بعد 0
torch.sum(q,0)

tensor([11, 24, 21, 29])

In [131]:
#جمع تجمعی
torch.cumsum(q,1)

tensor([[ 1,  9, 15, 20],
        [ 3, 11, 17, 26],
        [ 2,  7, 10, 16],
        [ 5,  8, 14, 23]])

In [132]:
#درایه های کنار هم از هم کم میکنه
torch.diff(q)

tensor([[ 7, -2, -1],
        [ 5, -2,  3],
        [ 3, -2,  3],
        [-2,  3,  3]])

In [134]:
#تمام المان های ارایه را در هم ضرب میکنه
torch.prod(q,1)

tensor([ 240, 1296,  180,  810])

In [135]:
torch.sqrt(q)

tensor([[1.0000, 2.8284, 2.4495, 2.2361],
        [1.7321, 2.8284, 2.4495, 3.0000],
        [1.4142, 2.2361, 1.7321, 2.4495],
        [2.2361, 1.7321, 2.4495, 3.0000]])

In [137]:
#باقیمانده تقسیم بد عدد داده شده رو میده
torch.remainder(q,torch.tensor(5))

tensor([[1, 3, 1, 0],
        [3, 3, 1, 4],
        [2, 0, 3, 1],
        [0, 3, 1, 4]])

In [141]:
#رند میکنه به نزدیکترین عدد
torch.round(q)

tensor([[1, 8, 6, 5],
        [3, 8, 6, 9],
        [2, 5, 3, 6],
        [5, 3, 6, 9]])

In [142]:
torch.ceil(q)

tensor([[1, 8, 6, 5],
        [3, 8, 6, 9],
        [2, 5, 3, 6],
        [5, 3, 6, 9]])

In [144]:
torch.floor(q)

tensor([[1, 8, 6, 5],
        [3, 8, 6, 9],
        [2, 5, 3, 6],
        [5, 3, 6, 9]])

In [146]:
# نرم میگیره یعنی درایه ها به توان 2 و جمع و در نهایت رادیکال
torch.norm(q.float())

tensor(23.2594)

In [148]:
#فاصله اقلیدسی بین دو تا تنسور بدست میاره
torch.dist(q.float() , torch.tensor(5))

tensor(9.5394)

In [150]:
torch.mean(q.float(), dim=1)

tensor([5.0000, 6.5000, 4.0000, 5.7500])

In [153]:
torch.std(q.float())

tensor(2.4418)

In [154]:
torch.var(q.float())

tensor(5.9625)

In [155]:
torch.exp(q.float())

tensor([[2.7183e+00, 2.9810e+03, 4.0343e+02, 1.4841e+02],
        [2.0086e+01, 2.9810e+03, 4.0343e+02, 8.1031e+03],
        [7.3891e+00, 1.4841e+02, 2.0086e+01, 4.0343e+02],
        [1.4841e+02, 2.0086e+01, 4.0343e+02, 8.1031e+03]])

In [156]:
torch.log(q.float())

tensor([[0.0000, 2.0794, 1.7918, 1.6094],
        [1.0986, 2.0794, 1.7918, 2.1972],
        [0.6931, 1.6094, 1.0986, 1.7918],
        [1.6094, 1.0986, 1.7918, 2.1972]])

In [173]:
l= torch.randint(10, (2,3))
print(l)
torch.min(l , dim=0)

tensor([[0, 1, 8],
        [6, 0, 7]])


torch.return_types.min(
values=tensor([0, 0, 7]),
indices=tensor([0, 1, 1]))

In [174]:
torch.argmin(l)

tensor(0)

In [175]:
#چند تای بزرگتر بده
torch.topk(l , 2)

torch.return_types.topk(
values=tensor([[8, 1],
        [7, 6]]),
indices=tensor([[2, 1],
        [2, 0]]))

In [176]:
#چند تای کوچیکتر بده
torch.topk(l , 2, largest= False)

torch.return_types.topk(
values=tensor([[0, 1],
        [0, 6]]),
indices=tensor([[0, 1],
        [1, 0]]))

In [178]:
torch.mode(l)

torch.return_types.mode(
values=tensor([0, 0]),
indices=tensor([0, 1]))

In [179]:
torch.median(l)

tensor(1)

In [ ]:
#### torch to numpy

In [180]:
#a.numpy()
#a= a.cuda()

RuntimeError: The NVIDIA driver on your system is too old (found version 9020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

In [ ]:
a.cpu().numpy()

In [ ]:
#### numpy to torch

In [181]:
import numpy as np
b= np.array([1,2,3])
b

array([1, 2, 3])

In [182]:
torch.tensor(b)

tensor([1, 2, 3], dtype=torch.int32)

In [183]:
torch.from_numpy(b)

tensor([1, 2, 3], dtype=torch.int32)